import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { signIn,signOut, useSession } from "next-auth/client";

export default function Home() {
  const [session]=useSession()
  console.log(session)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
<div>

        <button onClick={()=>signIn()}>sign in</button>
        <button onClick={()=>signOut()}>sign out</button>
        <div>{process.env.GOOGLE_ID}</div>
        <div>{process.env.GOOGLE_SECRET}</div>
        <div>{process.env.NEXT_AUTH}</div>
        <div>{process.env.NODE_ENV}</div>
</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
